version: "3.9"

services:
  aspnet:
    build:
      context: ./aspnet-backend
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      - mlapi

  mlapi:
    build:
      context: ./fastapi-ml
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  # angular:
  #   image: node:18
  #   working_dir: /app
  #   volumes:
  #     - ./angular-frontend:/app
  #   command: sh -c "npm install && npm run start"
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - aspnet